import classNames from "classnames";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const MENU_ITEMS = [
  {
    title: "About",
    url: "/about",
  },
  {
    title: "Musings",
    url: "/musings",
  },
  {
    title: "Podcast",
    url: "/podcast",
  },
  {
    title: "Stack",
    url: "/stack",
  },
  {
    title: "Grit",
    url: "/grit",
  },
];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);

  const handleBurgerClick = () => {
    setMenuOpen(!menuOpen);
  };
  return (
    <>
      <Head>
        <title>Emily Xu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header
        className={classNames(styles.header, menuOpen && styles.menuopen)}
      >
        <div className={styles.name}>
          <span>Emily Xu</span>
          <button className={styles.burger} onClick={handleBurgerClick}>
            X
          </button>
        </div>
        <nav className={styles.menu}>
          <ul className={styles.menulist}>
            {MENU_ITEMS.map(({ url, title }) => {
              return (
                <li key={url}>
                  <Link href={url}>{title}</Link>
                </li>
              );
            })}
          </ul>
        </nav>
        <div className={styles.actions}>
          <button className={styles.button}>subscribe</button>
        </div>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
}
